package com.dental.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VerlichtingUIDesign extends GridLayout {
    protected Button bVoordeurBuiten;
    protected Button bInkom;
    protected Button bInkomVloer;
    protected Button bLedBureau;
    protected Button bLedKeuken;
    protected Button bGarage;
    protected Button bBureau1;
    protected Button bBureau2;
    protected Button bLeeshoek;
    protected Button bKeuken;
    protected Button bEettafel;
    protected Button bKeuken2;
    protected Button bSpotsKeuken;
    protected Button bLivingTV;
    protected Button bLiving;
    protected Button bNachthall;
    protected Button bNachthallBovenVloer;
    protected Button bTrapVerlichting;
    protected Button bTuin1;
    protected Button bTuin2;
    protected Button bTuin3;

    public VerlichtingUIDesign() {
        Design.read(this);
    }
}
